{
  "__language__": "bash",
  "__output__": [
    "result",
    "bytes",
    null
  ],
  "a": [
    "int",
    null,
    "08d2d6aba49b53a764f897cf54cc0984e6568e3081d4dc31936eff54d90e79bd"
  ],
  "b": [
    "int",
    null,
    "607ad8c0dbe89ff9463bf8a99a2224486a0c8e5c2171d49988a9af1a70175e0f"
  ],
  "code": [
    "text",
    null,
    "705ce03beca8fe9c9c5555d28e3bf7c0bbd1ef4dd2ed3ebeb063308a9eda1328"
  ]
}

Traceback (most recent call last):
  File "/cwd/workflow-core/transformation-raw-bash.py", line 57, in <module>
    asyncio.get_event_loop().run_until_complete(build_transformation())
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/cwd/workflow-core/transformation-raw-bash.py", line 42, in build_transformation
    result = await transformation_cache.run_transformation_async(
  File "/seamless/seamless/workflow/core/cache/transformation_cache.py", line 1378, in run_transformation_async
    raise self.transformation_exceptions[tf_checksum]
seamless.workflow.core.transformation.SeamlessTransformationError: Traceback (most recent call last):
  File "transformer", line 8, in <module>
    from seamless.core.transformation import SeamlessStreamTransformationError
ModuleNotFoundError: No module named 'seamless.core'
*************************************************
Execution time: 0.0 seconds

