<Silk: {'b': 12} > {'b': 12}
<class 'silk.Silk.Silk'> <class 'dict'>
<Silk: {'b': 12} > {'b': 12} {'properties': {'b': {'type': 'number'}}, 'type': 'object'}
<Silk: 32 >
<Silk: {'x': 12, 'y': 20} >

Stage 2
<Silk: {'c': 20, 'd': 32, 'f': 20, 'g': 50} >
Stage 3
<Silk: {'c': 7, 'd': 19, 'f': 20, 'g': 50} >
Stage 4
<Silk: 309 >
Stage 5
<Silk: {'c': 8, 'd': -4, 'f': 20, 'g': 50} >
<Silk: 326 >
Stage 6
VALIDATE <Silk: {'g': 50, 'c': 8, 'd': -4, 'f': 20} >
Stage 7
VALIDATE <Silk: {'g': 50, 'c': 8, 'd': 108, 'f': 20} >
<Silk: None >
<Silk: None >
jsonschema.exceptions.ValidationError: 
************************************************************************
*  Silk validation error
************************************************************************
Traceback (most recent call last):
  File "/silk/silk/validation/validators.py", line 237, in validator_validators
    validator_func(silkobject)
  File "Silk validator 1", line 4, in validator
    assert self.f > self.d
AssertionError
************************************************************************


Failed validating 'validators' in schema:
    {'properties': {'c': {}, 'd': {}, 'f': {}, 'g': {}},
     'type': 'object',
     'validators': [{'code': 'def validator(self):\n'
                             '    print("VALIDATE", self)\n'
                             '    assert self.g > self.c + self.f\n'
                             '    assert self.f > self.d\n',
                     'language': 'python',
                     'name': 'validator'}]}

On instance:
    {'g': 50, 'c': 8, 'd': 108, 'f': 20}

Stage 8
VALIDATE <Silk: {'g': 50, 'c': 8, 'd': 88, 'f': 20} >
<Silk: None >
<Silk: None >
jsonschema.exceptions.ValidationError: 
************************************************************************
*  Silk validation error
************************************************************************
Traceback (most recent call last):
  File "/silk/silk/validation/validators.py", line 237, in validator_validators
    validator_func(silkobject)
  File "Silk validator 1", line 4, in validator
    assert self.f > self.d
AssertionError
************************************************************************


Failed validating 'validators' in schema:
    {'properties': {'c': {}, 'd': {}, 'f': {}, 'g': {}},
     'type': 'object',
     'validators': [{'code': 'def validator(self):\n'
                             '    print("VALIDATE", self)\n'
                             '    assert self.g > self.c + self.f\n'
                             '    assert self.f > self.d\n',
                     'language': 'python',
                     'name': 'validator'}]}

On instance:
    {'g': 50, 'c': 8, 'd': 88, 'f': 20}

Stage 9
VALIDATE <Silk: {'g': 50, 'c': 8, 'd': 12, 'f': 20} >
<Silk: {'c': 8, 'd': 12, 'f': 20, 'g': 50} >
<Silk: 342 >
